### ISSUE TITLE
JavaScript critical error at line 25, column 48002 in https://unpkg.com/v-tooltip\n\nSCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by dn978** [Akryum/v-tooltip#656] opened 2021-03-08 17:55 UTC
The tool tip failed on IE. it worked fine with Chrome and Edge. How do I get around the issue? I am using VueJS version 2.5.16

**Comment by yavisht** [comment] 2021-03-10 22:52
@dn978 I can confirm this here's a temp fix - Lock versions

V-tooltip uses  ```vue-resize``` as a dependency. 
For now, downgrading the dependency versions fixed it for me, however its ideal to make it work with the latest release

```
"v-tooltip": "2.0.0-rc.33",
"vue-resize": "0.5.0",
```

**Comment by Akryum** [comment] 2021-03-10 23:55
Duplicate of #615

**Closed by Akryum** 2021-03-10 23:55 UTC

**Comment by dn978** [comment] 2021-03-11 13:03
I ended up going back to version prior to 2.10 and it worked without error. Thanks,
