### ISSUE TITLE
Moving the mouse around quickly makes popovers stay open

### ISSUE THREAD

**Issue by johnRivs** [Akryum/v-tooltip#220] opened 2019-03-22 12:06 UTC
How do I deal with this?
![](https://i.imgur.com/h9SOtrx.gif)

**Comment by rootman** [comment] 2019-03-26 09:01
I experience the same behavior, a fix is really appreciated, I will look into it as well.

**Comment by teuneboon** [comment] 2019-03-28 13:32
Have the same issue. It seems to be easier to reproduce if you do some async stuff with the tooltip, but not completely impossible if you don't.

**Comment by kabalage** [comment] 2019-03-31 09:47
I'm also having trouble with this problem. Delaying the tooltip makes it occure less frequently, but still very annoying. `:delay="{ show: 50, hide: 0 }"`

**Comment by rootman** [comment] 2019-04-02 16:34
I feel like I have found and solved the issue, it was due to requestAnimationFrame.

**Comment by pmochine** [comment] 2019-04-07 14:53
@rootman I hope this works and will be merged 🙈The bug is quite annyoing^^

**Comment by Akryum** [comment] 2019-04-11 13:33
Closed in #228

**Closed by Akryum** 2019-04-11 13:33 UTC
