### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by luisgserrano** [Akryum/v-tooltip#145] opened 2018-08-30 14:55 UTC
Hi @Akryum ,

My problem is that I have a list of boxes, very close between each other, and the popover should show when hovering each box. When I scroll very quickly, some popovers keep his open state as true and stay in the DOM.
I need to scroll to that box and hover -> leave again for the popover disappear.

Do you have a clue on this?

Best regards,
Luis Serrano.

**Comment by ivansieder** [comment] 2018-08-31 08:27
Hi @luisgserrano,

the best I could think about right now is that if your users usually move up/down with the mouse, then you could position the tooltip/popover on the left/right, to avoid the mouse getting over the tooltip itself and blocking the displaying of the next one.

Another option would be to add a feasible offset to allow some distance from one element to the next.

Other than that, I suppose this is related to an update delay in popper.js (due to performance issues). Because if you update every millisecond, the whole thing will really get laggy. And with a small delay, this can be avoided.

Do you have any codesandbox example ready, so I could look into it and maybe find another way around?

**Comment by luisgserrano** [comment] 2018-08-31 09:39
Hi @ivansieder, thanks for your time!

I will check popper.js options so I can get a solution, if not I will create a codesandbox example for you to check.

Many thanks,
Luís.

**Comment by luisgserrano** [comment] 2018-08-31 10:46
@ivansieder check it out: https://codesandbox.io/s/p31l7zn4j0

**Comment by luisgserrano** [comment] 2018-08-31 10:47
Scroll quick and you'll see many popovers are still in the dom and showing. 
It's supposed to hide onMouseLeave.

**Comment by ivansieder** [comment] 2018-09-10 08:30
@luisgserrano does that issue persist for you also if you use v-tooltip instead of a popover?

**Comment by luisgserrano** [comment] 2018-09-21 09:56
@ivansieder no. Only using popover.

**Comment by dated** [comment] 2018-12-21 13:45
This needs an additional scroll event listener. Since technically the mouse does not move while scrolling, the mouse leave event is not fired.

**Comment by luisgserrano** [comment] 2018-12-23 19:36
@dated what is your solution? Just set the disposeTimeout as 0?

**Comment by dated** [comment] 2018-12-23 19:57
i have none at the moment. time permitting i'll submit a pr with the additional listener here.

**Comment by Akryum** [comment] 2019-04-28 23:19
Duplicate of #99

**Closed by Akryum** 2019-04-28 23:19 UTC

**Comment by gertjanwytynck** [comment] 2019-10-17 09:09
@dated Did you eventually solved this? Or how did you tackle this? I have exact the same problem, I would like to hide all popovers on scroll event, as scrolling fast keeps the popovers in the DOM.

Thanks in advance.

**Comment by dated** [comment] 2019-10-17 09:12
No, unfortunately I haven't looked at it further. I "solved" it by setting the tooltip container, which was enough of a fix for the case at hand, see https://github.com/ArkEcosystem/desktop-wallet/pull/824

**Comment by gertjanwytynck** [comment] 2019-10-17 09:23
Thanks for the fast response. Let me try if this does the job in my case.
