### ISSUE TITLE
Tooltips stuck when applied to many elements

### ISSUE THREAD

**Issue by bmarkovic** [Akryum/v-tooltip#62] opened 2017-11-10 07:24 UTC
Hello,

We use v-tooltip on a table display providing additional information on cell data with the tooltip. In this scenario, in some browsers tooltips get stuck when the user goes over multiple cells to "pinpoint" the one he's interested in and the overall efect is that something is broken.

Here is a JSFiddle that emulates our scenario:

https://jsfiddle.net/sy8hshaL/

I've had more luck reproducing it with Firefox than with Chrome.

**Comment by floriansimon1** [comment] 2017-11-13 12:38
Have you found out the cause of this problem?

**Comment by Akryum** [comment] 2017-11-13 12:40
Not yet. 😄

**Comment by capeck** [comment] 2017-11-13 17:27
I have the same issue as well, will be interested to know of the solution.

**Closed** 2017-11-14 12:31 UTC
Labels: bug

**Comment by floriansimon1** [comment] 2017-11-15 13:41
Excellent work @Akryum, thanks!
