### ISSUE TITLE
How to set width of v-popup component?

### ISSUE THREAD

**Issue by PrimozRome** [Akryum/v-tooltip#179] opened 2019-01-12 10:53 UTC
Is it even possible or is limited to those 200px or so?

**Comment by PrimozRome** [comment] 2019-01-21 12:21
Anyone?

**Comment by DBLaci** [comment] 2019-04-04 13:22
Duplicate of: https://github.com/Akryum/v-tooltip/issues/175

max-width on inner solved the problem for mi, but not for every size. 500px worked, but 800px started flickering the tooltip, so it's not perfect.

**Comment by Akryum** [comment] 2019-04-28 23:07
Duplicate of #175

**Closed by Akryum** 2019-04-28 23:07 UTC
