### ISSUE TITLE
Passing string as v-tooltip directive value causes TypeError in some browsers.

### ISSUE THREAD

**Issue by alza54** [Akryum/v-tooltip#333] opened 2019-08-17 15:37 UTC
When v-tooltip directive is used like suggested in Getting Started/Usage: `<button v-tooltip="'You have ' + count + ' new messages.'">`, a TypeError will be thrown in some browsers, for example in IE11.

First, after creating element with _v-tooltip_ directive, [_bind_](https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L190) function is called. Then, [_createTooltip_](https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L155) is called with string as _value_ argument. The function extracts content from _value argument_ and assigns it to a [constant](https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L156). After that, _content_ is assigned to _title_ parameter in [_opts_](https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L158) object. But.. original _value_ argument is used once again (_because when _value_ is an object, it should contain tooltip options_) in the same object ([_opts_](https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L158)) with **spread operator**. Using spread operator on a string is not allowed and will simply throw a SyntaxError: _Invalid or unexpected token_, although no one reported any issues, until now.

The issue exists, but it has been masked. 
Module is bundled using _rollup.js_ and transpiled with _Babel_. Babel creates [__defineProperty_](https://github.com/Akryum/v-tooltip/blob/master/dist/v-tooltip.esm.js#L40), [__objectSpread_](https://github.com/Akryum/v-tooltip/blob/master/dist/v-tooltip.esm.js#L55) functions definitions, and replaces all spread operators with __objectSpread_ function calls. __objectSpread_, when called, assumes every argument which is not null is an object, iterates over arguments and [gets](https://github.com/Akryum/v-tooltip/blob/master/dist/v-tooltip.esm.js#L58) arguments _own property names_ relying on **Object.keys()** method.
So, when directive is created with string as value, the _Object.keys()_ is executed on a string (without any need). Most modern browsers can execute _Object.keys()_ on a string, number, without any problems. 
IE (11) **can't**. For IE, an argument really must be an _Object_.
Chrome/Firefox/Chromium based browsers behavior:
`> Object.keys('hello world')`
`< ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]`
IE behavior:
`> Object.keys('hello world')`
`< [TypeError]: Object.keys: argument is not an Object`

Even tough, passing _value_ into the [options](https://github.com/Akryum/v-tooltip/blob/master/src/directives/v-tooltip.js#L160) on modern browsers is completely unnecessary, since it will only pass:
`> _objectSpread({}, 'hello world', { placement: 'top' })`
`< {0: "1", 1: "2", 2: "3", placement: "top"}` object into _getOptions_ method, which will ignore all unknown parameters.

**Comment by Akryum** [comment] 2020-12-30 21:29
Duplicate of #323

**Closed by Akryum** 2020-12-30 21:29 UTC
