### ISSUE TITLE
index.d.ts : Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

### ISSUE THREAD

**Issue by lifenautjoe** [Akryum/v-tooltip#473] opened 2020-02-26 10:26 UTC
Hey there. 

I believe there's an issue with the provided typings.

```
 ERROR  ERROR in /Users/lifenautjoe/Documents/code/okuna/okuna-web/node_modules/v-tooltip/types/index.d.ts(3,1):
3:1 Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
    1 | import Vue, { VueConstructor, DirectiveOptions, PluginFunction } from 'vue';
    2 |
  > 3 | const vToolTip: PluginFunction<any>;
      | ^
```

Running this with Nuxt 

```
"nuxt": "2.11.0",
```

and typescript runtime

```
"@nuxt/typescript-runtime": "0.3.8",
```

**Comment by Pandazaur** [comment] 2020-03-03 10:58
Hello, I had the same issue.

It looks like the `types` folder was added in the `v2.0.3`. I temporarily downgraded to the `v2.0.2` to make my build possible

**Comment by T0TProduction** [comment] 2020-03-03 13:03
the error is related to [this issue in Typescript](https://github.com/microsoft/TypeScript/issues/3792)

tried to create a fix, but couldn't do so quickly.
I guess downgrading to v2.0.2 is the way to go until TS finally supports these typings.

**Comment by backbone87** [comment] 2020-03-30 09:48
> the error is related to this issue in Typescript

while it is related, the correct way is to use `declare const vToolTip: ...` since you can actually init anything in `.d.ts` files. (`const vToolTip: PluginFunction<any>;` isnt even valid js)

**Comment by PatrickSachs** [comment] 2020-05-29 12:13
What's the status on this PR? For now I've created a fork and fixed this manually but I'd rather depend on this version than my own monkey patched one

**Comment by Szymon-dziewonski** [comment] 2020-08-10 08:11
Also rising question what is the status ?

**Comment by ahules** [comment] 2020-08-17 07:05
Have the same problem.

**Comment by Rossomasha** [comment] 2020-08-17 07:14
Hi. I have the same issue. Have to downgrade the version to `v2.0.2`.

**Comment by heggi** [comment] 2020-08-17 08:25
Adding to package.json `"v-tooltip": "github:Akryum/v-tooltip#pull/464/head",` as temporary solution

**Comment by andrewsmith1996** [comment] 2020-08-24 12:45
Same issue here, downgrading to v2.0.2 works for me.

**Comment by gabrielmtns** [comment] 2020-09-21 23:54
downgrading to v2.0.2 not works for me :(

**Comment by Akryum** [comment] 2020-12-30 22:24
Duplicate of #459

**Closed by Akryum** 2020-12-30 22:24 UTC
