### ISSUE TITLE
Vue app build is broken 

### ISSUE THREAD

**Issue by mayank30** [Akryum/v-tooltip#468] opened 2020-02-04 18:09 UTC
types/index.d.ts

**const vToolTip: PluginFunction<any>;**

It should be export appended on top of it .

**Comment by rijkvanzanten** [comment] 2020-02-07 20:50
For reference, this is the error that's returned:

```
ERROR in /path/to/node_modules/v-tooltip/types/index.d.ts(3,1):
3:1 Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
    1 | import Vue, { VueConstructor, DirectiveOptions,
 PluginFunction } from 'vue';
    2 | 
  > 3 | const vToolTip: PluginFunction<any>;
      | ^
    4 | export default vToolTip;
    5 | 
    6 | export const VPopover: VueConstructor<Vue>;
```

**Comment by rijkvanzanten** [comment] 2020-02-07 20:50
https://github.com/Akryum/v-tooltip/pull/464 is a fix for this issue

**Comment by elwin013** [comment] 2020-11-13 22:23
Until #464 (or sth similar) is merged local solution is here - https://github.com/Akryum/v-tooltip/issues/459#issuecomment-727064463

**Comment by Akryum** [comment] 2020-12-30 22:22
Duplicate of #459

**Closed by Akryum** 2020-12-30 22:22 UTC
